# Generated by Django 5.2.16 on 2026-07-07 19:31

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=280)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('is_official', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_of_interest',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='pois.pointofinterest')),
            ],
            options={
                'db_table': 'poi_checkins',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pois.pointofinterest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poi_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['city'], name='points_of_i_city_5e71fa_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['categories'], name='points_of_i_categor_e1ca40_gin'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-created_at'], name='poi_checkin_user_id_b7659e_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('poi', 'user'), name='uq_review_per_user_poi'),
        ),
    ]
