# Generated by Django 5.2.16 on 2026-07-07 19:31

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pois', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('route_type', models.CharField(choices=[('auto', 'Auto'), ('semi_auto', 'Semi Auto'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('transport_mode', models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('driving', 'Driving'), ('transit', 'Transit'), ('mixed', 'Mixed')], default='walking', max_length=16)),
                ('theme_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('total_distance_meters', models.PositiveIntegerField(default=0)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('is_public', models.BooleanField(default=False)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('parent_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routes.route')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=16)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='routes.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_collaborators',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField()),
                ('stay_duration_minutes', models.PositiveIntegerField(default=0)),
                ('custom_note', models.TextField(blank=True)),
                ('transport_to_next', models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('driving', 'Driving'), ('transit', 'Transit'), ('mixed', 'Mixed')], default='walking', max_length=16)),
                ('distance_to_next_meters', models.PositiveIntegerField(default=0)),
                ('duration_to_next_minutes', models.PositiveIntegerField(default=0)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='pois.pointofinterest')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='routes.route')),
            ],
            options={
                'db_table': 'route_points',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='routes.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_routes',
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_public', '-published_at'], name='routes_is_publ_cfd4a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='routecollaborator',
            constraint=models.UniqueConstraint(fields=('route', 'user'), name='uq_route_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='routepoint',
            constraint=models.UniqueConstraint(fields=('route', 'order_index'), name='uq_route_order'),
        ),
        migrations.AddConstraint(
            model_name='savedroute',
            constraint=models.UniqueConstraint(fields=('route', 'user'), name='uq_saved_route'),
        ),
    ]
